name: Check Draft

on:
  pull_request:
    branches:
     - main
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  fail-for-draft:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'draft')
    steps:
      - name: Fail if PR is a draft
        run: |
          echo "This PR is currently a draft."
          exit 1
  fail-for-draft2:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'bug')
    steps:
      - name: Pass if PR is a bug
        run: |
          echo "This PR is currently ready to merge."
